apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: main
      image: gitopsworkshop/my-app:v2
      imagePullPolicy: IfNotPresent
      env:
      - name: GREETING
        value: "Hello world 5"

